name: observability

services:
- name: viewer
  executable: dapr
  args: run --app-id viewer --app-port 5000 --components-path ../components/local -- dotnet run --project ./viewer.csproj --urls "http://localhost:5000"
  workingDirectory: ./viewer/

- name: processor
  executable: dapr
  args: run --app-id processor --app-port 5030 --components-path ../components/local -- dotnet run --project ./processor.csproj --urls "http://localhost:5030"
  workingDirectory: ./processor/
  # env_file:
  #   - ../components/local/local.env

- name: provider
  executable: dapr
  args: run --app-id provider --app-port 5040 --components-path ../components/local -- dotnet run --project ./provider.csproj --urls "http://localhost:5040"
  workingDirectory: ./provider/
