apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: twittersecretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "/home/pyadmin/.secrets/secrets.json"
    